# Project Information
site_name: My Wiki
site_description: 
site_author: 
site_url: 
strict: true

# Repository
#repo_name: 'OI-wiki/OI-wiki'
#repo_url: 'https://github.com/OI-wiki/OI-wiki'
#edit_uri: 'https://oi-wiki.org/edit-landing/?ref='

# Copyright
copyright: 'Copyright &copy; 2016 - 2020 My Wiki'
google_analytics:
  - 'UA-124485594-1'
  - 'auto'

# Contents
nav:
  - 简介:
    - Getting Started: index.md
  - 网络:
    - PDUR: COM/pdur.md
  #- 诊断:
  - 存储:
    - NVM: NVM/nvm.md
  - 以太网:
    - 组播: ETH/Multicast.md
    - ENET-ISR: ETH/EthISR.md 
  - 基础模块:
    - 链接文件: BASE/link_file.md
  - 错误总结:
    - ECC错误: ERROR/ecc_error.md
  #- MCal:

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  favicon: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'

  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'
  disqus: 'OI-Wiki'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''
  # notice:
  #   title: 'Hi'
  #   message: '欢迎点击这里对 OI Wiki 提一点建议'
  #   url: 'https://wj.qq.com/s2/4467592/b1e9'
  #   position: 'topCenter'
  #   progressBar: false
  #   timeout: false

extra_javascript:
  - '_static/js/extra.js?v=16'
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'


extra_css:
  - '_static/css/extra.css?v=13'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
