@startuml NVM_FSM

[*] --> NVM_STATE_UNINIT

NVM_STATE_UNINIT -> NVM_STATE_UNINIT : true


NVM_STATE_IDLE --> NVM_STATE_NORMAL_PRIO_JOB : 1 NVM_QRY_ID_NORMAL_PRIO_JOB
NVM_STATE_IDLE --> NVM_STATE_MULTI_BLOCK_JOB : 2 NVM_QRY_ID_MULTI_BLK_JOB
NVM_STATE_IDLE --> NVM_STATE_IDLE : 3 true

NVM_STATE_NORMAL_PRIO_JOB --> NVM_STATE_NORMAL_PRIO_JOB : 1 NVM_QRY_ID_MAIN_FSM_RUNNING
NVM_STATE_NORMAL_PRIO_JOB --> NVM_STATE_IDLE : 2 true

NVM_STATE_MULTI_BLOCK_JOB --> NVM_STATE_IDLE : 1 NVM_QR_ID_WRITEALL_KILLED
NVM_STATE_MULTI_BLOCK_JOB --> NVM_STATE_MULTI_BLOCK_JOB : 2 NVM_QRY_ID_MAIN_FSM_RUNNING
NVM_STATE_MULTI_BLOCK_JOB --> NVM_STATE_IDLE : 3 true

NVM_STATE_READ_READ_DATA --> NVM_STATE_READ_READ_DATA : 1 NVM_QRY_ID_NV_BUSY
NVM_STATE_READ_READ_DATA --> NVM_STATE_READ_CMP_CRC : 2 NVM_QRY_ID_LAST_RESULT_OK && NVM_QRY_ID_CRC_BUSY
NVM_STATE_READ_READ_DATA --> NVM_STATE_READ_DATA_VALIDATION : 3 NVM_QRY_ID_LAST_RESULT_OK
NVM_STATE_READ_READ_DATA --> NVM_STATE_READ_IMPL_RECOV : else
NVM_STATE_READ_READ_DATA : NVM_STATE_READ_READ_DATA
NVM_STATE_READ_READ_DATA : NVM_STATE_READ_READ_DATA
NVM_STATE_READ_READ_DATA : NVM_STATE_READ_READ_DATA
NVM_STATE_READ_READ_DATA : NVM_STATE_READ_READ_DATA
NVM_STATE_READ_READ_DATA : NVM_STATE_READ_READ_DATA



NVM_STATE_READ_DATA_VALIDATION ---> NVM_STATE_READ_FINALIZE : 1 NVM_QRY_SYNCDECRYPT && NVM_QRY_POST_READ_TRANSFORM
NVM_STATE_READ_DATA_VALIDATION ---> NVM_STATE_READ_DATA_VALIDATION : 2 NVM_QRY_CSM_RETRIES_NECESSARY
NVM_STATE_READ_DATA_VALIDATION ---> NVM_STATE_READ_IMPL_RECOV : 3 true

NVM_STATE_READ_CMP_CRC ---> NVM_STATE_READ_CMP_CRC : 1 NVM_QRY_ID_CRC_BUSY
NVM_STATE_READ_CMP_CRC ---> NVM_STATE_READ_DATA_VALIDATION : 2 NVM_QRY_ID_CRC_MATCH
NVM_STATE_READ_CMP_CRC ---> NVM_STATE_READ_IMPL_RECOV : 3 true

NVM_STATE_READ_IMPL_RECOV ---> NVM_STATE_READ_READ_DATA : 1 NVM_QRY_ID_REDUNDANT_BLOCK
NVM_STATE_READ_IMPL_RECOV ---> NVM_STATE_READ_LOAD_ROM : 2 true

NVM_STATE_READ_LOAD_ROM ---> NVM_STATE_READ_LOAD_ROM : 1 NVM_QRY_ID_DATA_COPY_BUSY
NVM_STATE_READ_LOAD_ROM ---> NVM_STATE_FSM_FINISHED : 2 true

NVM_STATE_READ_FINALIZE ----> NVM_STATE_READ_FINALIZE : 1 NVM_QRY_ID_DATA_COPY_BUSY
NVM_STATE_READ_FINALIZE ----> NVM_STATE_FSM_FINISHED : 2 true

NVM_STATE_WRITE_INITIAL ----> NVM_STATE_WRITE_INITIAL : 1 NVM_QRY_ID_DATA_COPY_BUSY
NVM_STATE_WRITE_INITIAL ----> NVM_STATE_WRITE_CRCCALC : 2 NVM_QRY_SYNCENCRYPT
NVM_STATE_WRITE_INITIAL ----> NVM_STATE_WRITE_INITIAL : 3 NVM_QRY_CSM_RETRIES_NECESSARY
NVM_STATE_WRITE_INITIAL ----> NVM_STATE_FSM_FINISHED : else
NVM_STATE_WRITE_INITIAL : NVM_STATE_WRITE_INITIAL
NVM_STATE_WRITE_INITIAL : NVM_STATE_WRITE_INITIAL
NVM_STATE_WRITE_INITIAL : NVM_STATE_WRITE_INITIAL
NVM_STATE_WRITE_INITIAL : NVM_STATE_WRITE_INITIAL
NVM_STATE_WRITE_INITIAL : NVM_STATE_WRITE_INITIAL





NVM_STATE_WRITE_CRCCALC ----> NVM_STATE_WRITE_CRCCALC : 1 NVM_QRY_ID_CRC_BUSY
NVM_STATE_WRITE_CRCCALC ----> NVM_STATE_WRITE_TEST_PRI_READ : 2 NVM_QRY_ID_REDUNDANT_BLOCK
NVM_STATE_WRITE_CRCCALC ----> NVM_STATE_WRITE_CRCCOMPMECHANISM : 3 true

NVM_STATE_WRITE_CRCCOMPMECHANISM ----> NVM_STATE_FSM_FINISHED : 1 NvM_QRY_CRC_COMP_MECHANISM_SKIPWRITE
NVM_STATE_WRITE_CRCCOMPMECHANISM ----> NVM_STATE_WRITE_WR_DATA_CRC_2 : 2 true

NVM_STATE_WRITE_TEST_PRI_READ -----> NVM_STATE_WRITE_TEST_PRI_READ : 1 NVM_QRY_ID_NV_BUSY
NVM_STATE_WRITE_TEST_PRI_READ -----> NVM_STATE_WRITE_TEST_SEC_READ : 2 NVM_QRY_ID_REDUNDANT_BLOCK && NVM_QRY_ID_LAST_RESULT_OK
NVM_STATE_WRITE_TEST_PRI_READ -----> NVM_STATE_WRITE_WR_DATA_CRC_1 : 3 NVM_QRY_ID_REDUNDANT_BLOCK

NVM_STATE_WRITE_TEST_SEC_READ -----> NVM_STATE_WRITE_TEST_SEC_READ : 1 NVM_QRY_ID_NV_BUSY
NVM_STATE_WRITE_TEST_SEC_READ -----> NVM_STATE_FSM_FINISHED : 2 NVM_QRY_ID_LAST_RESULT_OK && NvM_QRY_CRC_COMP_MECHANISM_SKIPWRITE
NVM_STATE_WRITE_TEST_SEC_READ -----> NVM_STATE_WRITE_WR_DATA_CRC_1 : 3 NVM_QRY_ID_LAST_RESULT_OK
NVM_STATE_WRITE_TEST_SEC_READ -----> NVM_STATE_WRITE_WR_DATA_CRC_1 : else

NVM_STATE_WRITE_WR_DATA_CRC_1 -----> NVM_STATE_WRITE_WR_DATA_CRC_1 : 1 NVM_QRY_ID_NV_BUSY
NVM_STATE_WRITE_WR_DATA_CRC_1 -----> NVM_STATE_WRITE_WR_DATA_CRC_2 : 2 NVM_QRY_ID_LAST_RESULT_OK
NVM_STATE_WRITE_WR_DATA_CRC_1 -----> NVM_STATE_WRITE_WR_DATA_CRC_2 : 3 NVM_QRY_ID_WRITE_RETRIES_EXCEEDED
NVM_STATE_WRITE_WR_DATA_CRC_1 -----> NVM_STATE_WRITE_WR_DATA_CRC_1 : else

NVM_STATE_WRITE_WR_DATA_CRC_2 -----> NVM_STATE_WRITE_WR_DATA_CRC_2 : 1 NVM_QRY_ID_NV_BUSY
NVM_STATE_WRITE_WR_DATA_CRC_2 -----> NVM_STATE_FSM_FINISHED : 2 NVM_QRY_ID_LAST_RESULT_OK
NVM_STATE_WRITE_WR_DATA_CRC_2 -----> NVM_STATE_FSM_FINISHED : 3 NVM_QRY_ID_WRITE_RETRIES_EXCEEDED
NVM_STATE_WRITE_WR_DATA_CRC_2 -----> NVM_STATE_WRITE_WR_DATA_CRC_2 : else

NVM_STATE_RESTORE_LOAD_ROM -----> NVM_STATE_RESTORE_LOAD_ROM : 1 NVM_QRY_ID_DATA_COPY_BUSY
NVM_STATE_RESTORE_LOAD_ROM -----> NVM_STATE_FSM_FINISHED : 2 true
NVM_STATE_RESTORE_LOAD_ROM : NVM_STATE_RESTORE_LOAD_ROM
NVM_STATE_RESTORE_LOAD_ROM : NVM_STATE_RESTORE_LOAD_ROM
NVM_STATE_RESTORE_LOAD_ROM : NVM_STATE_RESTORE_LOAD_ROM
NVM_STATE_RESTORE_LOAD_ROM : NVM_STATE_RESTORE_LOAD_ROM
NVM_STATE_RESTORE_LOAD_ROM : NVM_STATE_RESTORE_LOAD_ROM


NVM_STATE_INVALIDATING_BLOCK ------> NVM_STATE_INVALIDATING_BLOCK : 1 NVM_QRY_ID_NV_BUSY
NVM_STATE_INVALIDATING_BLOCK ------> NVM_STATE_INVALIDATING_BLOCK : 2 NVM_QRY_ID_LAST_RESULT_OK && NVM_QRY_ID_REDUNDANT_BLOCK
NVM_STATE_INVALIDATING_BLOCK ------> NVM_STATE_FSM_FINISHED : 3 true
NVM_STATE_INVALIDATING_BLOCK : NVM_STATE_INVALIDATING_BLOCK
NVM_STATE_INVALIDATING_BLOCK : NVM_STATE_INVALIDATING_BLOCK
NVM_STATE_INVALIDATING_BLOCK : NVM_STATE_INVALIDATING_BLOCK
NVM_STATE_INVALIDATING_BLOCK : NVM_STATE_INVALIDATING_BLOCK
NVM_STATE_INVALIDATING_BLOCK : NVM_STATE_INVALIDATING_BLOCK



NVM_STATE_ERASE_ERASE_BLOCK -------> NVM_STATE_ERASE_ERASE_BLOCK : 1 NVM_QRY_ID_NV_BUSY
NVM_STATE_ERASE_ERASE_BLOCK -------> NVM_STATE_ERASE_ERASE_BLOCK : 2 NVM_QRY_ID_LAST_RESULT_OK && NVM_QRY_ID_REDUNDANT_BLOCK
NVM_STATE_ERASE_ERASE_BLOCK -------> NVM_STATE_FSM_FINISHED : 3 true
NVM_STATE_ERASE_ERASE_BLOCK : NVM_STATE_ERASE_ERASE_BLOCK
NVM_STATE_ERASE_ERASE_BLOCK : NVM_STATE_ERASE_ERASE_BLOCK
NVM_STATE_ERASE_ERASE_BLOCK : NVM_STATE_ERASE_ERASE_BLOCK
NVM_STATE_ERASE_ERASE_BLOCK : NVM_STATE_ERASE_ERASE_BLOCK
NVM_STATE_ERASE_ERASE_BLOCK : NVM_STATE_ERASE_ERASE_BLOCK

NVM_STATE_READALL_PROC_CONFIG_ID --------> NVM_STATE_READALL_PROC_CONFIG_ID : 1 NVM_QRY_ID_SUB_FSM_RUNNING
NVM_STATE_READALL_PROC_CONFIG_ID --------> NVM_STATE_READALL_PROC_RAM_BLOCK : 2 true
NVM_STATE_READALL_PROC_CONFIG_ID : NVM_STATE_READALL_PROC_CONFIG_ID
NVM_STATE_READALL_PROC_CONFIG_ID : NVM_STATE_READALL_PROC_CONFIG_ID
NVM_STATE_READALL_PROC_CONFIG_ID : NVM_STATE_READALL_PROC_CONFIG_ID
NVM_STATE_READALL_PROC_CONFIG_ID : NVM_STATE_READALL_PROC_CONFIG_ID
NVM_STATE_READALL_PROC_CONFIG_ID : NVM_STATE_READALL_PROC_CONFIG_ID

NVM_STATE_READALL_PROC_RAM_BLOCK --------> NVM_STATE_FSM_FINISHED : 1 NVM_QRY_ID_LAST_BLOCK_DONE_READALL
NVM_STATE_READALL_PROC_RAM_BLOCK --------> NVM_STATE_READALL_CHK_RAM_VALIDITY : 2 NVM_QRY_ID_RAM_VALID && NVM_QRY_ID_CRC_BUSY
NVM_STATE_READALL_PROC_RAM_BLOCK --------> NVM_STATE_READALL_KILLED : 3 NVM_QRY_READALL_KILLED
NVM_STATE_READALL_PROC_RAM_BLOCK --------> NVM_STATE_READALL_CHK_SKIP : else

NVM_STATE_READALL_CHK_SKIP --------> NVM_STATE_READALL_READABILITY_CHECK : 1 NVM_QRY_ID_SKIP_BLOCK && NVM_QRY_ID_WRITE_BLOCK_ONCE
NVM_STATE_READALL_CHK_SKIP --------> NVM_STATE_READALL_PROC_RAM_BLOCK : 2 NVM_QRY_ID_SKIP_BLOCK
NVM_STATE_READALL_CHK_SKIP --------> NVM_STATE_READALL_LOAD_DEFAULTS : 3 NVM_QRY_ID_EXT_RUNTIME
NVM_STATE_READALL_CHK_SKIP --------> NVM_STATE_READALL_READ_NV : else

NVM_STATE_READALL_KILLED --------> NVM_STATE_READALL_PROC_RAM_BLOCK : 1 NVM_QRY_ID_SKIP_BLOCK
NVM_STATE_READALL_KILLED --------> NVM_STATE_READALL_LOAD_DEFAULTS : 2 NVM_QRY_ID_HAS_ROM
NVM_STATE_READALL_KILLED --------> NVM_STATE_READALL_PROC_RAM_BLOCK : 3 true

NVM_STATE_READALL_WR_ONCE_PROT --------> NVM_STATE_READALL_PROC_RAM_BLOCK : 1 NVM_QRY_ID_LAST_RESULT_OK
NVM_STATE_READALL_WR_ONCE_PROT --------> NVM_STATE_READALL_READABILITY_CHECK : 2 NVM_QRY_ID_REDUNDANT_BLOCK
NVM_STATE_READALL_WR_ONCE_PROT --------> NVM_STATE_READALL_PROC_RAM_BLOCK : 3 true

NVM_STATE_READALL_CHK_RAM_VALIDITY --------> NVM_STATE_READALL_CHK_RAM_VALIDITY : 1 NVM_QRY_ID_CRC_BUSY
NVM_STATE_READALL_CHK_RAM_VALIDITY --------> NVM_STATE_READALL_PROC_RAM_BLOCK : 2 NVM_QRY_ID_CRC_MATCH
NVM_STATE_READALL_CHK_RAM_VALIDITY --------> NVM_STATE_READALL_KILLED : 3 NVM_QRY_READALL_KILLED
NVM_STATE_READALL_CHK_RAM_VALIDITY --------> NVM_STATE_READALL_CHK_SKIP : else

NVM_STATE_READALL_READ_NV ----------> NVM_STATE_READALL_KILLED : 1 NVM_QRY_ID_NV_BUSY && NVM_QRY_READALL_KILLED
NVM_STATE_READALL_READ_NV ----------> NVM_STATE_READALL_READ_NV : 2 NVM_QRY_ID_SUB_FSM_RUNNING
NVM_STATE_READALL_READ_NV ----------> NVM_STATE_READALL_PROC_RAM_BLOCK : 3 true

NVM_STATE_READALL_LOAD_DEFAULTS ----------> NVM_STATE_READALL_LOAD_DEFAULTS : 1 NVM_QRY_ID_SUB_FSM_RUNNING
NVM_STATE_READALL_LOAD_DEFAULTS ----------> NVM_STATE_READALL_PROC_RAM_BLOCK : 2 true

NVM_STATE_READALL_READABILITY_CHECK ----------> NVM_STATE_READALL_KILLED : 1 NVM_QRY_ID_NV_BUSY && NVM_QRY_READALL_KILLED
NVM_STATE_READALL_READABILITY_CHECK ----------> NVM_STATE_READALL_READABILITY_CHECK : 2 NVM_QRY_ID_NV_BUSY
NVM_STATE_READALL_READABILITY_CHECK ----------> NVM_STATE_READALL_WR_ONCE_PROT : 3 true

NVM_STATE_WRITEALL_PROC_BLOCK ----------> NVM_STATE_FSM_FINISHED : 1 NVM_QRY_ID_CANCEL_WRITE_ALL
NVM_STATE_WRITEALL_PROC_BLOCK ----------> NVM_STATE_WRITEALL_WAIT_MEMHWA : 2 NVM_QRY_ID_LAST_BLOCK_DONE_WRITEALL
NVM_STATE_WRITEALL_PROC_BLOCK ----------> NVM_STATE_WRITEALL_WRITE_FSM : 3 NVM_QRY_ID_BLK_RELEVANT_FOR_WRITE_ALL
NVM_STATE_WRITEALL_PROC_BLOCK ----------> NVM_STATE_WRITEALL_PROC_BLOCK : else
NVM_STATE_WRITEALL_PROC_BLOCK : NVM_STATE_WRITEALL_PROC_BLOCK
NVM_STATE_WRITEALL_PROC_BLOCK : NVM_STATE_WRITEALL_PROC_BLOCK
NVM_STATE_WRITEALL_PROC_BLOCK : NVM_STATE_WRITEALL_PROC_BLOCK
NVM_STATE_WRITEALL_PROC_BLOCK : NVM_STATE_WRITEALL_PROC_BLOCK
NVM_STATE_WRITEALL_PROC_BLOCK : NVM_STATE_WRITEALL_PROC_BLOCK

NVM_STATE_WRITEALL_WRITE_FSM ----------> NVM_STATE_WRITEALL_WRITE_FSM : 1 NVM_QRY_ID_SUB_FSM_RUNNING
NVM_STATE_WRITEALL_WRITE_FSM ----------> NVM_STATE_WRITEALL_PROC_BLOCK : 2 true 

NVM_STATE_WRITEALL_WAIT_MEMHWA ----------> NVM_STATE_FSM_FINISHED : 1 NVM_QRY_ID_CANCEL_WRITE_ALL
NVM_STATE_WRITEALL_WAIT_MEMHWA ----------> NVM_STATE_WRITEALL_WAIT_MEMHWA : 2 NVM_QRY_ID_MEMHWA_BUSY
NVM_STATE_WRITEALL_WAIT_MEMHWA ----------> NVM_STATE_FSM_FINISHED : 3 true
NVM_STATE_WRITEALL_WAIT_MEMHWA ----------> NVM_STATE_FSM_FINISHED : else

NVM_STATE_FSM_FINISHED ----> NVM_STATE_FSM_FINISHED : true
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
NVM_STATE_FSM_FINISHED : just for test
@enduml