@startuml NVM_FSM

[*] --> NVM_STATE_UNINIT

NVM_STATE_UNINIT -> NVM_STATE_UNINIT : 1 true
NVM_STATE_UNINIT -> NVM_STATE_UNINIT : 2 true
NVM_STATE_UNINIT -> NVM_STATE_UNINIT : 3 true
NVM_STATE_UNINIT -> NVM_STATE_UNINIT : else

NVM_STATE_IDLE --> NVM_STATE_NORMAL_PRIO_JOB : 1 NVM_QRY_ID_NORMAL_PRIO_JOB && true
NVM_STATE_IDLE --> NVM_STATE_MULTI_BLOCK_JOB : 2 NVM_QRY_ID_MULTI_BLK_JOB && true
NVM_STATE_IDLE --> NVM_STATE_IDLE : 3 true
NVM_STATE_IDLE --> NVM_STATE_IDLE : else

NVM_STATE_NORMAL_PRIO_JOB -> NVM_STATE_NORMAL_PRIO_JOB : 1 NVM_QRY_ID_MAIN_FSM_RUNNING && true
NVM_STATE_NORMAL_PRIO_JOB -> NVM_STATE_IDLE : 2 true
NVM_STATE_NORMAL_PRIO_JOB -> NVM_STATE_IDLE : 3 true
NVM_STATE_NORMAL_PRIO_JOB -> NVM_STATE_IDLE : else

NVM_STATE_MULTI_BLOCK_JOB -> NVM_STATE_IDLE : 1 NVM_QR_ID_WRITEALL_KILLED && true
NVM_STATE_MULTI_BLOCK_JOB -> NVM_STATE_MULTI_BLOCK_JOB : 2 NVM_QRY_ID_MAIN_FSM_RUNNING && true
NVM_STATE_MULTI_BLOCK_JOB -> NVM_STATE_IDLE : 3 true
NVM_STATE_MULTI_BLOCK_JOB -> NVM_STATE_IDLE : else

NVM_STATE_READ_READ_DATA -> NVM_STATE_READ_READ_DATA : 1 NVM_QRY_ID_NV_BUSY && true
NVM_STATE_READ_READ_DATA -> NVM_STATE_READ_CMP_CRC : 2 NVM_QRY_ID_LAST_RESULT_OK && NVM_QRY_ID_CRC_BUSY
NVM_STATE_READ_READ_DATA -> NVM_STATE_READ_DATA_VALIDATION : 3 NVM_QRY_ID_LAST_RESULT_OK && true
NVM_STATE_READ_READ_DATA -> NVM_STATE_READ_IMPL_RECOV : else

NVM_STATE_READ_DATA_VALIDATION -> NVM_STATE_READ_FINALIZE : 1 NVM_QRY_SYNCDECRYPT && NVM_QRY_POST_READ_TRANSFORM
NVM_STATE_READ_DATA_VALIDATION -> NVM_STATE_READ_DATA_VALIDATION : 2 NVM_QRY_CSM_RETRIES_NECESSARY && true 
NVM_STATE_READ_DATA_VALIDATION -> NVM_STATE_READ_IMPL_RECOV : 3 true
NVM_STATE_READ_DATA_VALIDATION -> NVM_STATE_READ_IMPL_RECOV : else

NVM_STATE_READ_CMP_CRC -> NVM_STATE_READ_CMP_CRC
NVM_STATE_READ_CMP_CRC -> NVM_STATE_READ_DATA_VALIDATION
NVM_STATE_READ_CMP_CRC -> NVM_STATE_READ_IMPL_RECOV
NVM_STATE_READ_CMP_CRC -> NVM_STATE_READ_IMPL_RECOV


























@enduml